---
title: "BLH Gut Diversity in Potato"
author: "Riley M. Anderson"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output:
  github_document:
    toc: yes
    toc_depth: 5
    pandoc_args: --webtex
  html_document:
    keep_md: yes
    theme: readable
    mathjax: default
  html_notebook:
    code_folding: hide
    theme: readable
    mathjax: default
  pdf_document:
    toc: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = F,
    fig.height = 4, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = 'png', dev.args = list(pdf = list(onefile = F)))

```


```{r Main_Code, include = F, cache = F}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Setup - This code is run, but output is hidden
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Load Packages
library(tidyverse) # Needed for data wrangling: dplyr, tidyr, ggplot2
library(cowplot) # Needed for publication-quality ggplots
library(vegan)
library(sjPlot)
library(ggridges)
library(knitr)
library(ggExtra)
library(ggrepel)
library(gamm4)


# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Import datasets
dat1 <- read.csv("data/gut_contents.csv")

crop_type <- read.csv("data/crop_types.csv")


# Functions

# this function is useful for arranging ridge plots by time
Mode <- function(x) {
  # ensure input is a numeric vector
  if (!is.numeric(x)) {
    stop("Input must be a numeric vector.")
  }

  # create a table of frequencies
  freq_table <- table(x)

  # identify the maximum frequency
  max_freq <- max(freq_table)

  # extract the values that have the maximum frequency
  modes <- as.numeric(names(freq_table[freq_table == max_freq]))

  # return the first mode in case of ties (multimodality)
  return(modes[1])
}
```


```{r Data_Wrangling, echo = F, comment = ""}

dat1 <- dat1 %>% 
  filter(!is.na(BCTV),
         Year != 2022) %>% 
  mutate(Date = as.Date(Date, origin = "1899-12-30"),
         across(c(BLH_ID, type, family, common_name,
                genus, organism, primer, time_period, Year, CPt,
                region, site_name, host_plant, BCTV), factor)) %>% 
  # correcting typos in time_period
  mutate(time_period = case_when(
    time_period == " August" ~ "August",
    time_period == " April" ~ "April",
    time_period == " July" ~ "July",
    time_period == " June" ~ "June",
    time_period == " March" ~ "March",
    time_period == " May" ~ "May",
    time_period == " October" ~ "October",
    TRUE ~ time_period),
         time_period = factor(time_period,
                              levels = c("March", "April", "May",
                                         "June", "July", "August",
                                         "October")))

meta_dat <- dat1 %>% 
  select(-type : -blh_mix_count, -region_original,
         -S_citri, -site_name) %>% 
  filter(!is.na(CPt)) %>% 
  distinct() %>% 
  mutate(co_infected = factor(case_when(
    BCTV == "1" & CPt == "1" ~ "1",
    BCTV == "0" | CPt == "0" ~ "0",
    TRUE ~ NA)),
    Month = month(Date),
    sample_date = scale(yday(Date)))

crop_type_potato <- data.frame(genus = "Solanum",
                               crop_type = "crop")

crop_type <- bind_rows(crop_type, crop_type_potato) %>% 
  mutate(crop_type = factor(crop_type))

```



## Summary stats:


### Infections by host plant (plant that BLH was collected from)
```{r BLH_infections_by_host_plant, echo = F}

infected_blh_per_plant <- dat1 %>% 
  select(BLH_ID, Year, host_plant, BCTV, CPt) %>% 
  distinct() %>% 
  mutate(healthy = case_when(
    BCTV == 0 & CPt == 0 ~ 1,
    TRUE ~ 0),
    co_infected = case_when(
      BCTV == 1 & CPt == 1 ~ 1,
      TRUE ~ 0),
    BCTV = as.numeric(BCTV) - 1,
    CPt = as.numeric(CPt) - 1) %>% 
  filter(!is.na(CPt)) %>% 
  group_by(host_plant) %>% 
  summarise(n_bctv = sum(BCTV),
            n_cpt = sum(CPt),
            n_healthy = sum(healthy),
            n_coinfected = sum(co_infected))


total_blh_per_plant <- dat1 %>% 
  select(BLH_ID, Year, host_plant, BCTV, CPt) %>% 
  distinct() %>% 
  group_by(host_plant) %>% 
  tally() %>% 
  left_join(., infected_blh_per_plant, by = "host_plant") %>% 
  rename("Host plant" = host_plant,
         Total = n,
         BCTV = n_bctv,
         CPt = n_cpt,
         Healthy = n_healthy,
         "Co-infected" = n_coinfected)

total_w_c_t <- dat1 %>% 
  semi_join(., crop_type, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  mutate(BCTV = as.numeric(BCTV) - 1,
         CPt = as.numeric(CPt) - 1,
         co_infected = (case_when(
                        BCTV == 1 & CPt == 1 ~ 1,
                        BCTV != 1 | CPt != 1 ~ 0)),
         healthy = case_when(
                        BCTV == 0 & CPt == 0 ~ 1,
                        TRUE ~ 0)) %>% 
  group_by(genus, BCTV, CPt, co_infected, healthy) %>% 
  tally() %>%
  mutate(status = case_when(
    healthy == 1 ~ "Healthy",
    CPt == 1 & co_infected == 0 ~ "CPt",
    BCTV == 1 & co_infected == 0 ~ "BCTV",
    co_infected == 1 ~ "Co-infected"
  )) %>%  
  left_join(., crop_type, by = "genus") %>% 
  mutate(crop_type = case_when(
    crop_type == "crop" ~ "Crops",
    crop_type == "non crop" ~ "Non crops",
    crop_type == "tree" ~ "Trees"
  ), crop_type = factor(crop_type,
             levels = c("Non crops", "Crops", "Trees"))) %>% 
  group_by(crop_type, genus) %>% 
  summarise(total = sum(n))

kable(total_blh_per_plant,
      format = "markdown",
      digits = 2)

```


### Table of plants found in guts and their proportions and counts:
```{r plant_table, echo = T}

plant_table <- dat1 %>% select(family, genus) %>% 
  group_by(family, genus) %>% 
  tally(name = "detections") %>% 
  mutate(percent = round(detections / nrow(dat1), 4) * 100) %>% 
  arrange(desc(percent))

kable(plant_table,
      format = "markdown",
      digits = 2)

# number of families found:
dat1 %>% 
  select(family) %>% distinct() %>% nrow()

# number of genera found:
dat1 %>% 
  select(genus) %>% distinct() %>% nrow()

# number of tested BLH:
dat1 %>% uncount(blh_mix_count) %>% select(BLH_ID) %>% 
  distinct() %>% nrow()

# infection status of positive S. citri BLH:
dat1 %>% uncount(blh_mix_count) %>% 
  filter(!is.na(S_citri)) %>% 
  filter(S_citri == 1) %>% 
  select(BLH_ID, BCTV, CPt, S_citri, Year) %>% distinct()

# number of non-infectious:
dat1 %>% uncount(blh_mix_count) %>% 
  select(BLH_ID, BCTV, CPt, S_citri) %>% distinct() %>% 
  mutate(S_citri = case_when(
    S_citri == 1 ~ 1,
    TRUE ~ 0
  )) %>% 
  filter(BCTV != 1 & CPt != 1 & S_citri != 1) %>% nrow()

# number of BCTV only:
dat1 %>% uncount(blh_mix_count) %>% 
  select(BLH_ID, BCTV, CPt, S_citri) %>% distinct() %>% 
  mutate(S_citri = case_when(
    S_citri == 1 ~ 1,
    TRUE ~ 0
  )) %>% 
  filter(BCTV == 1 & CPt != 1 & S_citri != 1) %>% nrow()

# number of CPt only:
dat1 %>% uncount(blh_mix_count) %>% 
  select(BLH_ID, BCTV, CPt, S_citri) %>% distinct() %>% 
  mutate(S_citri = case_when(
    S_citri == 1 ~ 1,
    TRUE ~ 0
  )) %>% 
  filter(BCTV != 1 & CPt == 1 & S_citri != 1) %>% nrow()

# number of BCTV & CPt:
dat1 %>% uncount(blh_mix_count) %>% 
  select(BLH_ID, BCTV, CPt, S_citri) %>% distinct() %>% 
  mutate(S_citri = case_when(
    S_citri == 1 ~ 1,
    TRUE ~ 0
  )) %>% 
  filter(BCTV == 1 & CPt == 1) %>% nrow()

# number of N. tenellus collected in 2020:
dat1 %>% uncount(blh_mix_count) %>% 
  select(BLH_ID, Year) %>% 
  distinct() %>% 
  filter(Year == "2020") %>% nrow()


# percents of crop type (anything not in the crop_type.csv is considered a weed)
dat1 %>% uncount(blh_mix_count) %>% 
  left_join(., crop_type, by = "genus") %>% 
  mutate(crop_type = factor(case_when(
    is.na(crop_type) ~ "non crop",
    TRUE ~ crop_type
  ))) %>% 
  group_by(crop_type) %>% 
  tally() %>% 
  mutate(prop = round(n / sum(n), 4) * 100)

```



# Figure 2

```{r plant_inf_props, echo = F, fig.width=10, fig.height=6}
  
prop_inf_A <- dat1 %>% 
  semi_join(., crop_type, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  mutate(BCTV = as.numeric(BCTV) - 1,
         CPt = as.numeric(CPt) - 1,
         co_infected = (case_when(
                        BCTV == 1 & CPt == 1 ~ 1,
                        BCTV != 1 | CPt != 1 ~ 0)),
         healthy = case_when(
                        BCTV == 0 & CPt == 0 ~ 1,
                        TRUE ~ 0)) %>% 
  group_by(genus, BCTV, CPt, co_infected, healthy) %>% 
  tally() %>%
  mutate(status = case_when(
    healthy == 1 ~ "Healthy",
    CPt == 1 & co_infected == 0 ~ "CPt",
    BCTV == 1 & co_infected == 0 ~ "BCTV",
    co_infected == 1 ~ "Co-infected"
  )) %>% 
  select(-BCTV : -healthy) %>% 
  left_join(., crop_type, by = "genus") %>% 
  mutate(crop_type = case_when(
    crop_type == "crop" ~ "Crops",
    crop_type == "non crop" ~ "Non crops",
    crop_type == "tree" ~ "Trees"
  ), crop_type = factor(crop_type,
             levels = c("Non crops", "Crops", "Trees"))) %>% 
  ggplot(aes(x = fct_reorder2(genus, status, n),
             y = n,
             fill = factor(status,
                           level = c("Healthy", "BCTV",
                                      "CPt", "Co-infected")))) +
  geom_bar(stat = "identity", show.legend = F) +
  facet_wrap(~ crop_type, scales = "free") +
  coord_flip() +
  theme_bw(base_size = 18) +
  scale_fill_viridis_d(option = "G", direction = -1) +
  theme(strip.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) 

prop_inf_B <- dat1 %>% 
  semi_join(., crop_type, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  mutate(BCTV = as.numeric(BCTV) - 1,
         CPt = as.numeric(CPt) - 1,
         co_infected = (case_when(
                        BCTV == 1 & CPt == 1 ~ 1,
                        BCTV != 1 | CPt != 1 ~ 0)),
         healthy = case_when(
                        BCTV == 0 & CPt == 0 ~ 1,
                        TRUE ~ 0)) %>% 
  group_by(genus, BCTV, CPt, co_infected, healthy) %>% 
  tally() %>%
  mutate(status = factor(case_when(
    healthy == 1 ~ "Healthy",
    CPt == 1 & co_infected == 0 ~ "CPt",
    BCTV == 1 & co_infected == 0 ~ "BCTV",
    co_infected == 1 ~ "Co-infected"
  ))) %>%  
  left_join(., crop_type, by = "genus") %>% 
  mutate(crop_type = case_when(
    crop_type == "crop" ~ "Crops",
    crop_type == "non crop" ~ "Non crops",
    crop_type == "tree" ~ "Trees"
  ), crop_type = factor(crop_type,
             levels = c("Non crops", "Crops", "Trees"))) %>% 
  ungroup() %>% 
  select(-BCTV, -CPt, -co_infected, -healthy) %>% 
  pivot_wider(names_from = status, values_from = n,
              values_fill = list(n = 0)) %>% 
  select(-crop_type) %>% 
  left_join(., total_w_c_t, by = "genus") %>% 
  mutate(prop.healthy = Healthy / total,
         prop.CPt = CPt / total,
         prop.co = `Co-infected` / total,
         prop.bctv = BCTV / total) %>% 
  select(-Healthy, -CPt, -`Co-infected`, -BCTV) %>% 
  pivot_longer(cols = c(prop.healthy : prop.bctv),
               names_to = "status",
               values_to = "n") %>% 
  mutate(status = factor(case_when(
    status == "prop.healthy" ~ "Non-infectious",
    status == "prop.CPt" ~ "CPt",
    status == "prop.bctv" ~ "BCTV",
    status == "prop.co" ~ "Co-infected",
    TRUE ~ NA),
    levels = c("Non-infectious", "BCTV", "CPt", "Co-infected"))) %>% 
  ggplot(aes(x = n, y = status, fill = status)) +
  geom_violin() +
  scale_fill_viridis_d(option = "G", direction = -1) +
  facet_wrap(~crop_type) +
  theme_bw(base_size = 18) +
  theme(strip.background = element_blank(),
        strip.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom",
        axis.title = element_blank()) +
  scale_x_continuous(breaks = c(0, 0.5, 1),
                     limits = c(0, 1),)


cowplot::plot_grid(prop_inf_A, prop_inf_B,
                   nrow = 2,
                   align = "v",
                   rel_heights = c(2,1.2))
```

## Figure 2 stats:

```{r prop_infected_stats, echo = F}

inf_stat_data <- dat1 %>% 
  semi_join(., crop_type, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  mutate(BCTV = as.numeric(BCTV) - 1,
         CPt = as.numeric(CPt) - 1,
         co_infected = (case_when(
                        BCTV == 1 & CPt == 1 ~ 1,
                        BCTV != 1 | CPt != 1 ~ 0)),
         healthy = case_when(
                        BCTV == 0 & CPt == 0 ~ 1,
                        TRUE ~ 0)) %>% 
  group_by(genus, BCTV, CPt, co_infected, healthy) %>% 
  tally() %>%
  mutate(status = factor(case_when(
    healthy == 1 ~ "Healthy",
    CPt == 1 & co_infected == 0 ~ "CPt",
    BCTV == 1 & co_infected == 0 ~ "BCTV",
    co_infected == 1 ~ "Co-infected"
  ))) %>%  
  left_join(., crop_type, by = "genus") %>% 
  mutate(crop_type = case_when(
    crop_type == "crop" ~ "Crops",
    crop_type == "non crop" ~ "Non crops",
    crop_type == "tree" ~ "Trees"
  ), crop_type = factor(crop_type,
             levels = c("Non crops", "Crops", "Trees"))) %>% 
  ungroup() %>% 
  select(-BCTV, -CPt, -co_infected, -healthy) %>% 
  pivot_wider(names_from = status, values_from = n,
              values_fill = list(n = 0)) %>% 
  select(-crop_type) %>% 
  left_join(., total_w_c_t, by = "genus") %>% 
  mutate(prop.healthy = Healthy / total,
         prop.CPt = CPt / total,
         prop.co = `Co-infected` / total,
         prop.bctv = BCTV / total) %>% 
  select(-Healthy, -CPt, -`Co-infected`, -BCTV) %>% 
  pivot_longer(cols = c(prop.healthy : prop.bctv),
               names_to = "status",
               values_to = "n") %>% 
  mutate(status = factor(case_when(
    status == "prop.healthy" ~ "Healthy",
    status == "prop.CPt" ~ "CPt",
    status == "prop.bctv" ~ "BCTV",
    status == "prop.co" ~ "Co-infected",
    TRUE ~ NA),
    levels = c("Healthy", "BCTV", "CPt", "Co-infected"))) 

mod1 <- lm(n ~ status * crop_type, weights = total,
           data = inf_stat_data)

anova(mod1)

summary(mod1)

plot_model(mod1,
           type = "pred",
           terms = c("crop_type", "status"))
```

## Supplemental Figure 1

```{r supp_figure, echo = F, fig.height=16, fig.width=6}


supp_dat <- dat1 %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  mutate(BCTV = as.numeric(BCTV) - 1,
         CPt = as.numeric(CPt) - 1,
         co_infected = (case_when(
                        BCTV == 1 & CPt == 1 ~ 1,
                        BCTV != 1 | CPt != 1 ~ 0)),
         healthy = case_when(
                        BCTV == 0 & CPt == 0 ~ 1,
                        TRUE ~ 0)) %>% 
  group_by(genus, BCTV, CPt, co_infected, healthy) %>% 
  tally() %>%
  mutate(status = case_when(
    healthy == 1 ~ "Healthy",
    CPt == 1 & co_infected == 0 ~ "CPt",
    BCTV == 1 & co_infected == 0 ~ "BCTV",
    co_infected == 1 ~ "Co-infected"
  )) %>% 
  filter(!is.na(status))


supp_fig_A <- supp_dat %>% 
  group_by(genus) %>% 
  summarise(total_n = sum(n)) %>% 
  left_join(., supp_dat, by = "genus") %>% 
  ggplot(aes(x = fct_reorder2(genus, status, total_n),
             y = n,
             fill = factor(status,
                           level = c("Healthy", "BCTV",
                                      "CPt", "Co-infected")))) +
  geom_bar(stat = "identity", show.legend = F) +
  coord_flip() +
  scale_fill_viridis_d(option = "G", direction = -1) +
  theme_bw() +
  theme(legend.title = element_blank(),
        strip.background = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "bottom")

supp_fig_B <- dat1 %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  mutate(BCTV = as.numeric(BCTV) - 1,
         CPt = as.numeric(CPt) - 1,
         co_infected = (case_when(
                        BCTV == 1 & CPt == 1 ~ 1,
                        BCTV != 1 | CPt != 1 ~ 0)),
         healthy = case_when(
                        BCTV == 0 & CPt == 0 ~ 1,
                        TRUE ~ 0)) %>% 
  group_by(genus, BCTV, CPt, co_infected, healthy) %>% 
  tally() %>%
  mutate(status = factor(case_when(
    healthy == 1 ~ "Healthy",
    CPt == 1 & co_infected == 0 ~ "CPt",
    BCTV == 1 & co_infected == 0 ~ "BCTV",
    co_infected == 1 ~ "Co-infected"
  ))) %>% 
  filter(!is.na(status)) %>% 
  ungroup() %>% 
  select(-BCTV, -CPt, -co_infected, -healthy) %>% 
  pivot_wider(names_from = status, values_from = n,
              values_fill = list(n = 0)) %>% 
  mutate(total = CPt + Healthy + `Co-infected` + BCTV) %>% 
  mutate(prop.healthy = Healthy / total,
         prop.CPt = CPt / total,
         prop.co = `Co-infected` / total,
         prop.bctv = BCTV / total) %>% 
  select(-Healthy, -CPt, -`Co-infected`, -BCTV) %>% 
  pivot_longer(cols = c(prop.healthy : prop.bctv),
               names_to = "status",
               values_to = "n") %>% 
  mutate(status = factor(case_when(
    status == "prop.healthy" ~ "Non-infectious",
    status == "prop.CPt" ~ "CPt",
    status == "prop.bctv" ~ "BCTV",
    status == "prop.co" ~ "Co-infected",
    TRUE ~ NA),
    levels = c("Non-infectious", "BCTV", "CPt", "Co-infected"))) %>% 
  ggplot(aes(x = n, y = status, fill = status)) +
  geom_violin() +
  scale_fill_viridis_d(option = "G", direction = -1) +
  theme_bw() +
  theme(strip.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "bottom",
        axis.title = element_blank()) +
  scale_x_continuous(breaks = c(0, 0.5, 1),
                     limits = c(0, 1),)

cowplot::plot_grid(supp_fig_A, supp_fig_B,
                   nrow = 2,
                   align = "v",
                   rel_heights = c(2, 0.25))


```


# Figure 3

```{r ordination_prep, echo = F}

species_counts <- dat1 %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  group_by(BLH_ID, genus) %>% 
  tally() %>% 
  group_by(genus) %>% 
  summarise(total_counts = sum(n)) %>% 
  arrange(desc(total_counts)) %>% 
  filter(total_counts > quantile(total_counts, 0.9)) %>% 
  droplevels()

gut_matrix <- dat1 %>%
  semi_join(., species_counts, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  group_by(BLH_ID, genus) %>%
  tally() %>% 
  pivot_wider(names_from = genus,
              values_from = n,
              values_fill = list(n = 0)) %>% 
  left_join(., meta_dat, by = "BLH_ID") %>% 
  mutate(sample_date = yday(Date),
         healthy = factor(case_when(
           BCTV == 0 & CPt == 0 ~ "Healthy",
           TRUE ~ "Infected"
         ))) %>% 
  select(-Date)

gut_mat_species <- gut_matrix %>% ungroup() %>% 
  select(Kali : Lactuca)

gut_mat_predictors <- gut_matrix %>% ungroup() %>% 
  select(-Kali : -Lactuca)

```


## PERMANOVA

```{r PERMANOVA, echo = F}

#### checking for trends with PERMANOVA:

gut_ord_adonis1 <- adonis2(gut_mat_species ~
                            splines::ns(sample_date, df = 5) +
                             BCTV * Year + CPt + region,
                            strata = gut_matrix$host_plant,
                          data = gut_matrix)

gut_ord_adonis1

permutest(betadisper(vegdist(gut_mat_species, method = "bray"),
                     gut_matrix$BCTV))

simper_result <- simper(gut_mat_species,
                        group = gut_matrix$BCTV)
summary(simper_result)
```


## CAP with Isoclines:

```{r CAP_isoclines, echo = F, cache=FALSE}

cap_model <- capscale(gut_mat_species ~ BCTV,
                      data = gut_matrix,
                      distance = "bray")

summary(cap_model)

site_scoresI <- as.data.frame(scores(cap_model,
                                     display = "sites")) %>%
  mutate(sample = rownames(.),
         bctv = gut_matrix$BCTV)

site_scoresI$sample_date <- gut_matrix$sample_date

site_scoresI$host_plant <- gut_matrix$host_plant

gam_cap <- gamm4(log(sample_date) ~ s(CAP1, MDS1, k = 5),
                 random = ~(1 | host_plant),
                 data = site_scoresI)

grid_cap <- expand.grid(CAP1 = seq(min(site_scoresI$CAP1),
                                   max(site_scoresI$CAP1),
                                   length = 100),
                        MDS1 = seq(min(site_scoresI$MDS1),
                                   max(site_scoresI$MDS1),
                                   length = 100))

grid_cap$date_pred <- exp(predict(gam_cap$gam, newdata = grid_cap))


species_scores <- scores(cap_model, display = "species") %>%
  as.data.frame() %>%
  rownames_to_column("species")

# Keep only species with strongest loadings on CAP1
species_scores_filtered <- species_scores %>%
  filter(abs(CAP1) > 0.2 | abs(MDS1) > 0.2)


ggplot(site_scoresI,
       aes(x = CAP1, y = MDS1, color = bctv, fill = bctv)) +
  geom_point(shape = 21, size = 2, stroke = 0.5,
             aes(fill = bctv), color = 'black') +
  stat_ellipse(geom = "polygon", type = "t",
               level = 0.95, alpha = 0.3) +
  geom_contour(data = grid_cap, aes(x = CAP1,
                                    y = MDS1,
                                    z = date_pred),
               color = "grey40", inherit.aes = FALSE) +
  metR::geom_text_contour(data = grid_cap,
                          aes(x = CAP1, y = MDS1, z = date_pred),
                          color = "grey20", stroke = 0.2, skip = 1,
                          inherit.aes = FALSE) +
  scale_color_manual(values = c("0" = "#1b9e77", "1" = "#d95f02"),
                     labels = c("Non-infectious", "Infected")) +
  scale_fill_manual(values = c("0" = "#1b9e77", "1" = "#d95f02"),
                    labels = c("Non-infectious", "Infected")) +
  theme_minimal(base_size = 14) +
  labs(x = "CAP1 (BCTV--1.0%)",
       y = "MDS1 (Residual--24.1%)",
       fill = "BCTV", color = "BCTV") +
  geom_segment(data = species_scores_filtered,
               aes(x = 0, y = 0, xend = CAP1, yend = MDS1),
               arrow = arrow(length = unit(0.2, "cm")),
               color = "black",
               inherit.aes = F) +
  geom_text(data = species_scores_filtered,
            aes(x = CAP1 * 1.1, y = MDS1 * 1.1, label = species),
            size = 3, hjust = 0.5,
            inherit.aes = F)



```


# Figure 4

```{r plants_in_gut_time, echo = F, cache=F}

genus_orders <- dat1 %>% 
  semi_join(., crop_type, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  mutate(Week = week(Date)) %>% 
  group_by(genus) %>% 
  summarise(peak = Mode(Week)) %>% 
  arrange(desc(peak)) %>% data.frame() %>% 
  left_join(., crop_type, by = "genus")

crop_orders <- genus_orders %>% filter(crop_type == "crop") %>%
  droplevels() %>% 
  arrange(desc(peak)) %>% 
  select(genus)

crop_orders <- crop_orders$genus

non_crop_orders <- genus_orders %>%
  filter(crop_type == "non crop") %>%
  droplevels() %>% 
  arrange(desc(peak)) %>% 
  select(genus)

non_crop_orders <- non_crop_orders$genus

tree_orders <- genus_orders %>% filter(crop_type == "tree") %>%
  droplevels() %>% 
  arrange(desc(peak)) %>% 
  select(genus)

tree_orders <- tree_orders$genus

```


```{r crop_time, echo = F}

crop_counts <- dat1 %>%
  semi_join(., crop_type, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  left_join(., crop_type, by = "genus") %>% 
  filter(crop_type == "crop",
         genus != "Coriandrum" & genus != "Pisum" &
           genus != "Capsicum" & genus != "Cucurbita" &
           genus != "Spinacia") %>%
  droplevels() %>% 
  group_by(genus) %>% tally()

rpA <- dat1 %>%
  semi_join(., crop_type, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  left_join(., crop_type, by = "genus") %>% 
  filter(crop_type == "crop",
         genus != "Coriandrum" & genus != "Pisum" &
           genus != "Capsicum" & genus != "Cucurbita" &
           genus != "Spinacia") %>%
  droplevels() %>% 
  mutate(Week = week(Date)) %>%
  left_join(., crop_counts, by = "genus") %>% 
  ggplot(aes(x = Week,
             y = factor(genus, level = crop_orders),
             fill = genus)) +
  geom_density_ridges(aes(height = stat(density)),
                      scale = 4,
                      rel_min_height = 0.01,
                      stat = "density",
                      bw = "nrd0") +
  theme_ridges(grid = F) +
  theme(legend.position = "none") +
  scale_x_continuous(breaks = c(15, 25, 35),
                     labels = c("27 March",
                                "5 June",
                                "14 August")) +
  labs(x = "", y = "") +
  geom_vline(xintercept = 27.3,
             color = "grey50", linetype = "dashed") +
  annotate(geom = "text", x = 13, y = 9, label = " ") +
  annotate(geom = "text", x = 36, y = 9, label = " ") +
  annotate(geom = "text", x = 16, y = 8, label = "Spring",
           size = 5) +
  annotate(geom = "text", x = 32, y = 8, label = "Summer",
           size = 5) +
  geom_text(aes(y = genus, x = 40, label = n)) +
  scale_fill_viridis_d(option = "A")

```


```{r non_crop_time, echo = F}

noncrop_counts <- dat1 %>%
  semi_join(., crop_type, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  left_join(., crop_type, by = "genus") %>% 
  filter(crop_type == "non crop") %>%
  droplevels() %>% 
  group_by(genus) %>% tally()


rpB <- dat1 %>%
  semi_join(., crop_type, by = "genus") %>% 
  left_join(., crop_type, by = "genus") %>% 
  filter(crop_type == "non crop") %>% 
  droplevels() %>% 
  mutate(Week = week(Date)) %>%
  left_join(., noncrop_counts, by = "genus") %>% 
  ggplot(aes(x = Week,
             y = factor(genus, level = non_crop_orders),
             fill = genus)) +
  geom_density_ridges(aes(height = stat(density)),
                      scale = 4,
                      rel_min_height = 0.01,
                      stat = "density",
                      bw = "nrd0") +
  theme_ridges(grid = F) +
  theme(legend.position = "none") +
  scale_x_continuous(breaks = c(15, 25, 35),
                     labels = c("27 March",
                                "5 June",
                                "14 August")) +
  labs(x = "", y = "") +
  geom_vline(xintercept = 27.3,
             color = "grey50", linetype = "dashed") +
  annotate(geom = "text", x = 13, y = 15, label = " ") +
  annotate(geom = "text", x = 36, y = 15, label = " ") +
  annotate(geom = "text", x = 16, y = 14, label = "Spring",
           size = 5) +
  annotate(geom = "text", x = 32, y = 14, label = "Summer",
           size = 5) +
  geom_text(aes(y = genus, x = 41, label = n)) +
  scale_fill_viridis_d(option = "B")

```


```{r tree_time, echo = F}

tree_counts <- dat1 %>%
  semi_join(., crop_type, by = "genus") %>% 
  mutate(potato = factor(case_when(
    common_name == "Potato" ~ "potato",
    genus == "Solanum" & common_name != "potato" ~ "not_potato",
    TRUE ~ genus
  ))) %>% filter(potato != "not_potato") %>% 
  left_join(., crop_type, by = "genus") %>% 
  filter(crop_type == "tree",
         genus != "Salix") %>%
  droplevels() %>% 
  group_by(genus) %>% tally()


rpC <- dat1 %>%
  semi_join(., crop_type, by = "genus") %>% 
  left_join(., crop_type, by = "genus") %>% 
  filter(crop_type == "tree",
         genus != "Salix") %>%
  droplevels() %>% 
  mutate(Week = week(Date)) %>%
  left_join(., tree_counts, by = "genus") %>% 
  ggplot(aes(x = Week,
             y = factor(genus, level = tree_orders),
             fill = genus)) +
  geom_density_ridges(aes(height = stat(density)),
                      scale = 4,
                      rel_min_height = 0.01,
                      stat = "density",
                      bw = "nrd0") +
  theme_ridges(grid = F) +
  theme(legend.position = "none") +
  scale_x_continuous(breaks = c(15, 25, 35),
                     labels = c("27 March",
                                "5 June",
                                "14 August")) +
  labs(x = "", y = "") +
  geom_vline(xintercept = 27.3,
             color = "grey50", linetype = "dashed") +
  annotate(geom = "text", x = 13, y = 14, label = " ") +
  annotate(geom = "text", x = 36, y = 14, label = " ") +
  annotate(geom = "text", x = 16, y = 13, label = "Spring",
           size = 5) +
  annotate(geom = "text", x = 32, y = 13, label = "Summer",
           size = 5) +
  geom_text(aes(y = genus, x = 40, label = n)) +
  scale_fill_viridis_d(option = "C")

```

```{r ridgeplot_one_figure, echo = F, fig.height=11, fig.width=6}


cowplot::plot_grid(rpB, rpA, rpC,
                   nrow = 3,
                   align = "v",
                   labels = c("A", "B", "C"),
                   label_y = 1,
                   label_x = 0.21)

```


## Session Information

```{r Session_Info, echo = F, comment = ""}

# Add session information to help with reproduceability
sessionInfo()


```


